### ISSUE TITLE
Bug | Updating the name of a system does not update it neither in the Timeline nor the Investigated Systems

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#42] opened 2020-09-11 10:11 UTC
This will lead to inconsistencies when reporting. The update event might be needed to be grabbed somewhere to update that.

**Comment by cyb3rfox** [comment] 2020-09-11 13:00
Duplicate of #11

**Closed by cyb3rfox** 2020-09-11 13:00 UTC

**Comment by cyb3rfox** [comment] 2020-09-11 13:09
Wrong line. it'll require some major refactoring but has to come

**Comment by cyb3rfox** [comment] 2020-09-11 13:22
Duplicate of #17
